-- Tokyo Night Night
-- A Neovim Lua colorscheme ported from the original Vim definition

local M = {}

-- Color palette
M.palette = {
	bg = "#1a1b26",
	bg_context = "#2b2f44",
	bg_dark = "#16161e",
	bg_darker = "#1f1f29",
	bg_error = "#2d202a",
	bg_highlight = "#292e42",
	bg_hint = "#1a2b32",
	bg_info = "#192b38",
	bg_inlay = "#1d202d",
	bg_search = "#3d59a1",
	bg_select = "#343a55",
	bg_signature = "#20253a",
	bg_visual = "#283457",
	bg_warn = "#2e2a2d",
	blue = "#7aa2f7",
	blue0 = "#3d59a1",
	blue1 = "#2ac3de",
	blue2 = "#0db9d7",
	blue5 = "#89ddff",
	blue7 = "#394b70",
	border = "#15161e",
	brown = "#a58354",
	comment = "#565f89",
	cyan = "#7dcfff",
	dark3 = "#545c7e",
	dark5 = "#737aa2",
	diff_add_bg = "#243e4a",
	diff_change_bg = "#1f2231",
	diff_delete_bg = "#4a272f",
	fg = "#c0caf5",
	fg_dark = "#a9b1d6",
	fg_gutter = "#3b4261",
	git_add = "#449dab",
	git_change = "#6183bb",
	git_delete = "#914c54",
	git_ignore = "#565f89",
	green = "#9ece6a",
	green1 = "#73daca",
	green2 = "#41a6b5",
	magenta = "#bb9af7",
	magenta2 = "#ff007c",
	none = "NONE",
	orange = "#ff9e64",
	purple = "#9d7cd8",
	red = "#f7768e",
	red1 = "#db4b4b",
	teal = "#1abc9c",
	teal_dark = "#27a1b9",
	terminal_black = "#414868",
	white = "#ffffff",
	yellow = "#e0af68",
}

local C = M.palette

-- Highlight definitions
M.highlights = {
	-- Editor
	Bold = { fg = C.fg, bg = C.none, bold = true },
	ColorColumn = { bg = C.border },
	Conceal = { fg = C.dark5, bg = C.none },
	Cursor = { fg = C.bg, bg = C.fg },
	CursorIM = { fg = C.bg, bg = C.fg },
	Directory = { fg = C.blue, bg = C.none },
	EndOfBuffer = { fg = C.bg, bg = C.none },
	ErrorMsg = { fg = C.red1, bg = C.none },
	IncSearch = { fg = C.border, bg = C.orange },
	Italic = { fg = C.fg, bg = C.none, italic = true },
	LineNr = { fg = C.fg_gutter, bg = C.none },
	ModeMsg = { fg = C.fg_dark, bg = C.none, bold = true },
	MoreMsg = { fg = C.blue, bg = C.none },
	MsgArea = { fg = C.fg_dark, bg = C.none },
	NonText = { fg = C.dark3, bg = C.none },
	Normal = { fg = C.fg, bg = C.bg },
	Pmenu = { fg = C.fg, bg = C.bg_dark },
	Question = { fg = C.blue, bg = C.none },
	Search = { fg = C.fg, bg = C.blue0 },
	SignColumn = { fg = C.fg_gutter, bg = C.bg },
	StatusLine = { fg = C.fg_dark, bg = C.bg_dark },
	Substitute = { fg = C.border, bg = C.red },
	TabLine = { fg = C.fg_gutter, bg = C.bg_dark },
	Title = { fg = C.blue, bg = C.none, bold = true },
	Underlined = { bg = C.none, underline = true },
	VertSplit = { fg = C.border, bg = C.none },
	Visual = { bg = C.bg_visual },
	WarningMsg = { fg = C.yellow, bg = C.none },
	Whitespace = { fg = C.fg_gutter, bg = C.none },
	WildMenu = { bg = C.bg_visual },
	WinSeparator = { fg = C.border, bg = C.none, bold = true },
	debugPC = { bg = C.bg_dark },
	lCursor = { fg = C.bg, bg = C.fg },

	-- Syntax
	Character = { fg = C.green, bg = C.none },
	Comment = { fg = C.red, bg = C.none },
	Constant = { fg = C.orange, bg = C.none },
	Debug = { fg = C.orange, bg = C.none },
	Error = { fg = C.red1, bg = C.none },
	Function = { fg = C.blue, bg = C.none },
	Identifier = { fg = C.magenta, bg = C.none },
	Keyword = { fg = C.cyan, bg = C.none, italic = true },
	Operator = { fg = C.blue5, bg = C.none },
	PreProc = { fg = C.cyan, bg = C.none },
	Special = { fg = C.blue1, bg = C.none },
	Statement = { fg = C.magenta, bg = C.none },
	String = { fg = C.green, bg = C.none },
	Todo = { fg = C.bg, bg = C.yellow },
	Type = { fg = C.blue1, bg = C.none },

	-- Diagnostics
	ALEErrorSign = { fg = C.red1, bg = C.none },
	ALEWarningSign = { fg = C.yellow, bg = C.none },
	DiagnosticError = { fg = C.red1, bg = C.none },
	DiagnosticHint = { fg = C.teal, bg = C.none },
	DiagnosticInfo = { fg = C.blue2, bg = C.none },
	DiagnosticUnderlineError = { bg = C.none, sp = C.red1, undercurl = true },
	DiagnosticUnderlineHint = { bg = C.none, sp = C.teal, undercurl = true },
	DiagnosticUnderlineInfo = { bg = C.none, sp = C.blue2, undercurl = true },
	DiagnosticUnderlineWarn = { bg = C.none, sp = C.yellow, undercurl = true },
	DiagnosticUnnecessary = { fg = C.terminal_black, bg = C.none },
	DiagnosticVirtualTextError = { fg = C.red1, bg = C.bg_error },
	DiagnosticVirtualTextHint = { fg = C.teal, bg = C.bg_hint },
	DiagnosticVirtualTextInfo = { fg = C.blue2, bg = C.bg_info },
	DiagnosticVirtualTextWarn = { fg = C.yellow, bg = C.bg_warn },
	DiagnosticWarn = { fg = C.yellow, bg = C.none },

	-- Lsp
	CopilotAnnotation = { fg = C.terminal_black, bg = C.none },
	CopilotSuggestion = { fg = C.terminal_black, bg = C.none },
	IlluminatedWordRead = { bg = C.fg_gutter },
	IlluminatedWordText = { bg = C.fg_gutter },
	IlluminatedWordWrite = { bg = C.fg_gutter },
	LspCodeLens = { fg = C.git_ignore, bg = C.none },
	LspInfoBorder = { fg = C.teal_dark, bg = C.bg_dark },
	LspInlayHint = { fg = C.dark3, bg = C.bg_inlay },
	LspReferenceRead = { bg = C.fg_gutter },
	LspReferenceText = { bg = C.fg_gutter },
	LspReferenceWrite = { bg = C.fg_gutter },
	LspSignatureActiveParameter = { bg = C.bg_signature, bold = true },
	illuminatedCurWord = { bg = C.fg_gutter },
	illuminatedWord = { bg = C.fg_gutter },

	-- Git
	DiffAdd = { bg = C.diff_add_bg },
	DiffChange = { bg = C.diff_change_bg },
	DiffDelete = { bg = C.diff_delete_bg },
	DiffText = { bg = C.blue7 },
	GitGutterAdd = { fg = C.git_add, bg = C.none },
	GitGutterAddLineNr = { fg = C.git_add, bg = C.none },
	GitGutterChange = { fg = C.git_change, bg = C.none },
	GitGutterChangeLineNr = { fg = C.git_change, bg = C.none },
	GitGutterDelete = { fg = C.git_delete, bg = C.none },
	GitGutterDeleteLineNr = { fg = C.git_delete, bg = C.none },
	NeogitBranch = { fg = C.magenta, bg = C.none },
	NeogitDiffAddHighlight = { fg = C.git_add, bg = C.diff_add_bg },
	NeogitDiffContextHighlight = { fg = C.fg_dark, bg = C.bg_context },
	NeogitDiffDeleteHighlight = { fg = C.git_delete, bg = C.diff_delete_bg },
	NeogitHunkHeader = { fg = C.fg, bg = C.bg_highlight },
	NeogitHunkHeaderHighlight = { fg = C.blue, bg = C.fg_gutter },
	NeogitRemote = { fg = C.purple, bg = C.none },
	diffAdded = { fg = C.git_add, bg = C.diff_add_bg },
	diffChanged = { fg = C.git_change, bg = C.diff_change_bg },
	diffFile = { fg = C.blue, bg = C.none },
	diffIndexLine = { fg = C.magenta, bg = C.none },
	diffLine = { fg = C.git_ignore, bg = C.none },
	diffNewFile = { fg = C.blue1, bg = C.diff_add_bg },
	diffOldFile = { fg = C.blue1, bg = C.diff_delete_bg },
	diffRemoved = { fg = C.git_delete, bg = C.diff_delete_bg },

	-- Blink
	BlinkCmpDoc = { fg = C.fg, bg = C.bg_dark },
	BlinkCmpDocBorder = { fg = C.teal_dark, bg = C.bg_dark },
	BlinkCmpGhostText = { fg = C.terminal_black, bg = C.none },
	BlinkCmpKindCodeium = { fg = C.teal, bg = C.none },
	BlinkCmpKindCopilot = { fg = C.teal, bg = C.none },
	BlinkCmpKindDefault = { fg = C.fg_dark, bg = C.none },
	BlinkCmpKindSupermaven = { fg = C.teal, bg = C.none },
	BlinkCmpKindTabNine = { fg = C.teal, bg = C.none },
	BlinkCmpLabel = { fg = C.fg, bg = C.none },
	BlinkCmpLabelDeprecated = { fg = C.fg_gutter, bg = C.none, strikethrough = true },
	BlinkCmpLabelMatch = { fg = C.blue1, bg = C.none },
	BlinkCmpMenu = { fg = C.fg, bg = C.bg_dark },
	BlinkCmpMenuBorder = { fg = C.teal_dark, bg = C.bg_dark },
	BlinkCmpSignatureHelp = { fg = C.fg, bg = C.bg_dark },
	BlinkCmpSignatureHelpBorder = { fg = C.teal_dark, bg = C.bg_dark },

	-- Fzf
	FzfLuaBorder = { fg = C.teal_dark, bg = C.bg_dark },
	FzfLuaDirPart = { fg = C.fg_dark, bg = C.none },
	FzfLuaFzfNormal = { fg = C.fg, bg = C.none },
	FzfLuaFzfPointer = { fg = C.magenta2, bg = C.none },
	FzfLuaFzfSeparator = { fg = C.orange, bg = C.bg_dark },
	FzfLuaNormal = { fg = C.fg, bg = C.bg_dark },
	FzfLuaPreviewTitle = { fg = C.teal_dark, bg = C.bg_dark },
	FzfLuaTitle = { fg = C.orange, bg = C.bg_dark },
	Sneak = { fg = C.bg_highlight, bg = C.magenta },
	SneakScope = { bg = C.bg_visual },

	-- Neotest
	NeotestAdapterName = { fg = C.purple, bg = C.none, bold = true },
	NeotestBorder = { fg = C.blue, bg = C.none },
	NeotestDir = { fg = C.blue, bg = C.none },
	NeotestExpandMarker = { fg = C.fg_dark, bg = C.none },
	NeotestFailed = { fg = C.red, bg = C.none },
	NeotestFile = { fg = C.teal, bg = C.none },
	NeotestFocused = { fg = C.yellow, bg = C.none },
	NeotestIndent = { fg = C.fg_dark, bg = C.none },
	NeotestMarked = { fg = C.blue, bg = C.none },
	NeotestNamespace = { fg = C.green2, bg = C.none },
	NeotestPassed = { fg = C.green, bg = C.none },
	NeotestRunning = { fg = C.yellow, bg = C.none },
	NeotestSkipped = { fg = C.blue, bg = C.none },
	NeotestTarget = { fg = C.blue, bg = C.none },
	NeotestTest = { fg = C.fg_dark, bg = C.none },
	NeotestWinSelect = { fg = C.blue, bg = C.none },

	-- Vimwiki
	VimwikiHR = { fg = C.yellow, bg = C.none },
	VimwikiHeader1 = { fg = C.blue, bg = C.none, bold = true },
	VimwikiHeader2 = { fg = C.yellow, bg = C.none, bold = true },
	VimwikiHeader3 = { fg = C.green, bg = C.none, bold = true },
	VimwikiHeader4 = { fg = C.teal, bg = C.none, bold = true },
	VimwikiHeader5 = { fg = C.magenta, bg = C.none, bold = true },
	VimwikiHeader6 = { fg = C.purple, bg = C.none, bold = true },
	VimwikiHeader7 = { fg = C.orange, bg = C.none, bold = true },
	VimwikiHeader8 = { fg = C.red, bg = C.none, bold = true },
	VimwikiHeaderChar = { fg = C.yellow, bg = C.none },
	VimwikiLink = { fg = C.blue, bg = C.none },
	VimwikiList = { fg = C.orange, bg = C.none },
	VimwikiMarkers = { fg = C.blue, bg = C.none },
	VimwikiTag = { fg = C.green, bg = C.none },
	htmlH1 = { fg = C.magenta, bg = C.none, bold = true },
	htmlH2 = { fg = C.blue, bg = C.none, bold = true },

	-- Mini
	MiniAnimateCursor = { bg = C.none, nocombine = true },
	MiniCompletionActiveParameter = { bg = C.none, underline = true },
	MiniCursorword = { bg = C.fg_gutter },
	MiniCursorwordCurrent = { bg = C.fg_gutter },
	MiniDepsTitleError = { fg = C.border, bg = C.git_delete },
	MiniDepsTitleUpdate = { fg = C.border, bg = C.git_add },
	MiniDiffSignAdd = { fg = C.git_add, bg = C.none },
	MiniDiffSignChange = { fg = C.git_change, bg = C.none },
	MiniDiffSignDelete = { fg = C.git_delete, bg = C.none },
	MiniFilesFile = { fg = C.fg, bg = C.none },
	MiniFilesTitleFocused = { fg = C.teal_dark, bg = C.bg_dark, bold = true },
	MiniHipatternsFixme = { fg = C.border, bg = C.red1, bold = true },
	MiniHipatternsHack = { fg = C.border, bg = C.yellow, bold = true },
	MiniHipatternsNote = { fg = C.border, bg = C.teal, bold = true },
	MiniHipatternsTodo = { fg = C.border, bg = C.blue2, bold = true },
	MiniIconsAzure = { fg = C.blue2, bg = C.none },
	MiniIconsBlue = { fg = C.blue, bg = C.none },
	MiniIconsCyan = { fg = C.teal, bg = C.none },
	MiniIconsGreen = { fg = C.green, bg = C.none },
	MiniIconsGrey = { fg = C.fg, bg = C.none },
	MiniIconsOrange = { fg = C.orange, bg = C.none },
	MiniIconsPurple = { fg = C.purple, bg = C.none },
	MiniIconsRed = { fg = C.red, bg = C.none },
	MiniIconsYellow = { fg = C.yellow, bg = C.none },
	MiniIndentscopePrefix = { bg = C.none, nocombine = true },
	MiniIndentscopeSymbol = { fg = C.blue1, bg = C.none, nocombine = true },
	MiniJump = { fg = C.white, bg = C.magenta2 },
	MiniJump2dSpot = { fg = C.magenta2, bg = C.none, bold = true, nocombine = true },
	MiniJump2dSpotAhead = { fg = C.teal, bg = C.bg_dark, nocombine = true },
	MiniJump2dSpotUnique = { fg = C.orange, bg = C.none, bold = true, nocombine = true },
	MiniPickBorderText = { fg = C.teal, bg = C.bg_dark },
	MiniPickPrompt = { fg = C.blue2, bg = C.bg_dark },
	MiniStarterCurrent = { bg = C.none, nocombine = true },
	MiniStarterFooter = { fg = C.yellow, bg = C.none, italic = true },
	MiniStarterHeader = { fg = C.blue, bg = C.none },
	MiniStarterInactive = { fg = C.git_ignore, bg = C.none, italic = true },
	MiniStarterItem = { fg = C.fg, bg = C.bg },
	MiniStarterItemBullet = { fg = C.teal_dark, bg = C.none },
	MiniStarterItemPrefix = { fg = C.yellow, bg = C.none },
	MiniStarterQuery = { fg = C.blue2, bg = C.none },
	MiniStarterSection = { fg = C.blue1, bg = C.none },
	MiniStatuslineDevinfo = { fg = C.fg_dark, bg = C.fg_gutter },
	MiniStatuslineFileinfo = { fg = C.fg_dark, bg = C.fg_gutter },
	MiniStatuslineFilename = { fg = C.fg_dark, bg = C.bg_highlight },
	MiniStatuslineInactive = { fg = C.blue, bg = C.bg_dark },
	MiniStatuslineModeCommand = { fg = C.border, bg = C.yellow, bold = true },
	MiniStatuslineModeInsert = { fg = C.border, bg = C.green, bold = true },
	MiniStatuslineModeNormal = { fg = C.border, bg = C.blue, bold = true },
	MiniStatuslineModeOther = { fg = C.border, bg = C.teal, bold = true },
	MiniStatuslineModeReplace = { fg = C.border, bg = C.red, bold = true },
	MiniStatuslineModeVisual = { fg = C.border, bg = C.magenta, bold = true },
	MiniSurround = { fg = C.border, bg = C.orange },
	MiniTablineCurrent = { fg = C.fg, bg = C.fg_gutter },
	MiniTablineFill = { bg = C.border },
	MiniTablineHidden = { fg = C.dark5, bg = C.bg_dark },
	MiniTablineModifiedCurrent = { fg = C.yellow, bg = C.fg_gutter },
	MiniTablineModifiedHidden = { fg = C.brown, bg = C.bg_dark },
	MiniTablineModifiedVisible = { fg = C.yellow, bg = C.bg_dark },
	MiniTablineTabpagesection = { fg = C.none, bg = C.fg_gutter },
	MiniTablineVisible = { fg = C.fg, bg = C.bg_dark },
	MiniTestEmphasis = { bg = C.none, bold = true },
	MiniTestFail = { fg = C.red, bg = C.none, bold = true },
	MiniTestPass = { fg = C.green, bg = C.none, bold = true },
	MiniTrailspace = { bg = C.red },

	-- Glyphs
	GlyphPalette1 = { fg = C.red1, bg = C.none },
	GlyphPalette2 = { fg = C.green, bg = C.none },
	GlyphPalette3 = { fg = C.yellow, bg = C.none },
	GlyphPalette4 = { fg = C.blue, bg = C.none },
	GlyphPalette6 = { fg = C.green1, bg = C.none },
	GlyphPalette7 = { fg = C.fg, bg = C.none },
	GlyphPalette9 = { fg = C.red, bg = C.none },

	-- Misc
	ComplHint = { fg = C.terminal_black, bg = C.none },
	CursorColumn = { bg = C.bg_highlight },
	CursorLine = { bg = C.bg_highlight },
	CursorLineNr = { fg = C.orange, bg = C.none, bold = true },
	FloatBorder = { fg = C.teal_dark, bg = C.bg_dark },
	FloatTitle = { fg = C.teal_dark, bg = C.bg_dark },
	FoldColumn = { fg = C.git_ignore, bg = C.bg },
	Folded = { fg = C.blue, bg = C.fg_gutter },
	Foo = { fg = C.fg, bg = C.magenta2 },
	LineNrAbove = { fg = C.fg_gutter, bg = C.none },
	LineNrBelow = { fg = C.fg_gutter, bg = C.none },
	MatchParen = { fg = C.orange, bg = C.none, bold = true },
	NormalFloat = { fg = C.fg, bg = C.bg_dark },
	NormalNC = { fg = C.fg, bg = C.bg },
	NormalSB = { fg = C.fg_dark, bg = C.bg_dark },
	PmenuMatch = { fg = C.blue1, bg = C.bg_dark },
	PmenuMatchSel = { fg = C.blue1, bg = C.bg_select },
	PmenuSbar = { bg = C.bg_darker },
	PmenuSel = { bg = C.bg_select },
	PmenuThumb = { bg = C.fg_gutter },
	QuickFixLine = { bg = C.bg_visual, bold = true },
	SignColumnSB = { fg = C.fg_gutter, bg = C.bg_dark },
	SpecialKey = { fg = C.dark3, bg = C.none },
	SpellBad = { bg = C.none, sp = C.red1, undercurl = true },
	SpellCap = { bg = C.none, sp = C.yellow, undercurl = true },
	SpellLocal = { bg = C.none, sp = C.blue2, undercurl = true },
	SpellRare = { bg = C.none, sp = C.teal, undercurl = true },
	StatusLineNC = { fg = C.fg_gutter, bg = C.bg_dark },
	TabLineFill = { bg = C.border },
	TabLineSel = { fg = C.border, bg = C.blue },
	VisualNOS = { bg = C.bg_visual },
	debugBreakpoint = { fg = C.blue2, bg = C.bg_info },
	healthError = { fg = C.red1, bg = C.none },
	healthSuccess = { fg = C.green1, bg = C.none },
	healthWarning = { fg = C.yellow, bg = C.none },
	helpCommand = { fg = C.blue, bg = C.terminal_black },
	helpExample = { fg = C.git_ignore, bg = C.none },
	qfFileName = { fg = C.blue, bg = C.none },
	qfLineNr = { fg = C.dark5, bg = C.none },

	-- Links
	CurSearch = { link = "IncSearch" },
	Delimiter = { link = "Special" },
	FzfLuaCursor = { link = "IncSearch" },
	FzfLuaFilePart = { link = "FzfLuaFzfNormal" },
	FzfLuaFzfCursorLine = { link = "Visual" },
	FzfLuaHeaderText = { link = "Title" },
	FzfLuaPath = { link = "Directory" },
	LspKindColor = { link = "Special" },
	LspKindEvent = { link = "Special" },
	LspKindFile = { link = "Normal" },
	LspKindFolder = { link = "Directory" },
	LspKindSnippet = { link = "Conceal" },
	MiniAnimateNormalFloat = { link = "NormalFloat" },
	MiniClueBorder = { link = "FloatBorder" },
	MiniClueDescSingle = { link = "NormalFloat" },
	MiniClueTitle = { link = "FloatTitle" },
	MiniDepsChangeAdded = { link = "diffAdded" },
	MiniDepsChangeRemoved = { link = "diffRemoved" },
	MiniDepsHint = { link = "DiagnosticHint" },
	MiniDepsInfo = { link = "DiagnosticInfo" },
	MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
	MiniDepsPlaceholder = { link = "Comment" },
	MiniDepsTitle = { link = "Title" },
	MiniDepsTitleSame = { link = "Comment" },
	MiniDiffOverAdd = { link = "DiffAdd" },
	MiniDiffOverChange = { link = "DiffText" },
	MiniDiffOverContext = { link = "DiffChange" },
	MiniDiffOverDelete = { link = "DiffDelete" },
	MiniFilesBorder = { link = "FloatBorder" },
	MiniFilesCursorLine = { link = "CursorLine" },
	MiniFilesDirectory = { link = "Directory" },
	MiniFilesNormal = { link = "NormalFloat" },
	MiniFilesTitle = { link = "FloatTitle" },
	MiniJump2dDim = { link = "Comment" },
	MiniMapNormal = { link = "NormalFloat" },
	MiniMapSymbolCount = { link = "Special" },
	MiniMapSymbolLine = { link = "Title" },
	MiniNotifyBorder = { link = "FloatBorder" },
	MiniNotifyNormal = { link = "NormalFloat" },
	MiniNotifyTitle = { link = "FloatTitle" },
	MiniOperatorsExchangeFrom = { link = "IncSearch" },
	MiniPickBorder = { link = "FloatBorder" },
	MiniPickIconDirectory = { link = "Directory" },
	MiniPickMatchCurrent = { link = "CursorLine" },
	MiniPickMatchMarked = { link = "Visual" },
	MiniPickNormal = { link = "NormalFloat" },
	MiniPickPreviewLine = { link = "CursorLine" },
	MiniPickPreviewRegion = { link = "IncSearch" },
	WinBar = { link = "StatusLine" },
	WinBarNC = { link = "StatusLineNC" },
}

function M.load()
	vim.cmd("hi clear")
	if vim.fn.exists("syntax_on") then
		vim.cmd("syntax reset")
	end
	vim.g.colors_name = "tokyonight-night"
	vim.o.termguicolors = true

	for group, opts in pairs(M.highlights) do
		vim.api.nvim_set_hl(0, group, opts)
	end
end

return M
